### ISSUE TITLE
Redo Analysis: Segmentation Fault

### ISSUE THREAD

**Issue by rwiegan** [loosolab/jlu-bda-2020#33] opened 2021-03-26 16:17 UTC
I ran `python bin/tf_analyzer.py -g hg19 -b kidney -t ar -c chr1`
After successfully finishing the run i tried to redo the analysis with:
`python bin/tf_analyzer.py -g hg19 -b kidney -t ar -c chr1 -r`
This led to the following error:
```
Now starting normalisation process. 15 files will be normalised.
------ Log scaling files ------
- Log-scaling /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433194.chr1.bw (RAM usage: 0.61GB (1.4%))
- Log-scaling /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433194.chr1.bed (RAM usage: 0.61GB (1.4%))
- Log-scaling /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433193.chr1.bw (RAM usage: 0.61GB (1.4%))
- Log-scaling /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433193.chr1.bed (RAM usage: 0.61GB (1.4%))
- Log-scaling /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433192.chr1.bw (RAM usage: 0.61GB (1.4%))
- Log-scaling /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433192.chr1.bed (RAM usage: 0.61GB (1.4%))
- Log-scaling /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433191.chr1.bw (RAM usage: 0.61GB (1.4%))
- Log-scaling /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433191.chr1.bed (RAM usage: 0.61GB (1.4%))
- Log-scaling /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433189.chr1.bw (RAM usage: 0.61GB (1.4%))
- Log-scaling /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433189.chr1.bed (RAM usage: 0.61GB (1.4%))
- Log-scaling /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433190.chr1.bw (RAM usage: 0.61GB (1.4%))
- Log-scaling /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433190.chr1.bed (RAM usage: 0.61GB (1.4%))
- Log-scaling /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/atac-seq/E086-DNase.pval.signal.chr1.bw (RAM usage: 0.61GB (1.4%))
/mnt/workspace/rwiegan/git/jlu-bda-2020/bin/scripts/normalize_signal_values.py:182: RuntimeWarning: invalid value encountered in log
  log_values = numpy.log(signal_values)
- Log-scaling /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/atac-seq/E086-DNase.fc.signal.chr1.bw (RAM usage: 0.61GB (1.4%))
- Log-scaling /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/atac-seq/ENCFF107HEL.chr1.bw (RAM usage: 0.65GB (1.5%))
------ Finding global min/max values ------
- /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433194.chr1.bw.ln (RAM usage: 0.64GB (1.5%))
- /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433194.chr1.bed.ln (RAM usage: 0.64GB (1.5%))
- /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433193.chr1.bw.ln (RAM usage: 0.64GB (1.5%))
- /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433193.chr1.bed.ln (RAM usage: 0.64GB (1.5%))
- /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433192.chr1.bw.ln (RAM usage: 0.64GB (1.5%))
- /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433192.chr1.bed.ln (RAM usage: 0.64GB (1.5%))
- /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433191.chr1.bw.ln (RAM usage: 0.64GB (1.5%))
- /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433191.chr1.bed.ln (RAM usage: 0.64GB (1.5%))
- /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433189.chr1.bw.ln (RAM usage: 0.64GB (1.5%))
- /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433189.chr1.bed.ln (RAM usage: 0.64GB (1.5%))
- /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433190.chr1.bw.ln (RAM usage: 0.64GB (1.5%))
- /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/chip-seq/ar/SRX433190.chr1.bed.ln (RAM usage: 0.64GB (1.5%))
- /mnt/workspace/rwiegan/git/jlu-bda-2020/data/hg19/kidney/atac-seq/E086-DNase.pval.signal.chr1.bw.ln (RAM usage: 0.64GB (1.5%))
Segmentation fault
```

I reproduced the error by deleting the results and data folder and redoing the steps above.

**Comment by Jasmin-Walter** [comment] 2021-04-10 23:41
The error was caused by an error in normalization which led to empty .ln files. The error was fixed within the fix of the memory issue in commit 5050f3b.

**Closed as completed by Jasmin-Walter** 2021-04-10 23:41 UTC
Labels: bug
