### ISSUE TITLE
Exception: there is no data for your entered combination of genome, biosource and transcription factor

### ISSUE THREAD

**Issue by hschult** [loosolab/jlu-bda-2020#52] opened 2021-04-14 08:33 UTC
Call: `python bin/tf_analyzer.py -g mm9 -b liver`

Error:
```
fetching 20 ATAC/DNAse-seq experiments ...
fetching 8 ChIP-seq experiments ...
kept 20 ATAC/DNAse-seq experiments
0 lines added to /mnt/workspace/hschult/jlu-bda-2020/data/download/linking_table.csv
...
There is not data for biosource liver
Traceback (most recent call last):
  File "/mnt/workspace/hschult/jlu-bda-2020/bin/tf_analyzer.py", line 266, in <module>
    main()
  File "/mnt/workspace/hschult/jlu-bda-2020/bin/tf_analyzer.py", line 261, in main
    raise Exception(
Exception: there is no data for your entered combination of genome, biosource and transcription factor
```

I did a fresh installation with a new environment. The pipeline tells me that there are no valid combinations despite the call working before. Looking at the linking_table there are indeed no DNA-seq/ ATAC-seq listed, so the bug might be in the creation of the table? Also, I noticed that in former runs about 400 files were normalized whereas now there are only 76. This could be due to the missing ATAC-/DNA-seq but I'm not sure if that accounts for 80% of the files.

**Comment by kmlr81** [comment] 2021-04-15 09:28
The issue about only 76 files of previously 400 being normalized is caused by a fix on our end. We had an unnoctice bug that caused the pipe to write all files that had been downloaded in previous runs to be written into the normalization.csv to be normalized, if one of the arguments (-g -t -b or -c) was not specified by the user isntead of only including the files for the current analysis run. That has been fixed now and so the number of normalized files per run should have greately reduced in this case. The other problem is still being investigate.

**Comment by hschult** [comment] 2021-04-15 09:55
I was just thinking that this invalid combination error occurs relatively late in the pipeline. Assuming I select a combination where there is no matching ATAC or Chip. Will the pipeline still do all those steps before telling me that the combination doesn't work?

**Comment by Jasmin-Walter** [comment] 2021-04-15 18:15
The error was caused because the atac files were not added into the linking_table. It is fixed now.

Normally, if there is no ATAC/DNase or ChIP data, the pipeline stops before the creation of the csv. 
There are some cases, where there are no signal values within the bed files of the ChIP data. In this case, the files will be downloaded. However, they will not be transformed into bigwig files and therefor will not be normalized or analyzed.
There is also an exception within generate_pickle that stops the pipeline if there is no pickle file created for the current run.

**Closed as completed by Jasmin-Walter** 2021-04-15 18:15 UTC
